#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += st7701s_qhd480_960_dsi_vdo_boe_ips_guangtai_liangyong_r52.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
