#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += st7701s_fwvga_dsi_vdo_boe_shengshi_j106_bopai_b004_adc.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
